### ISSUE TITLE
[Feature] trigger next scan manually in WebUI

### ISSUE THREAD

**Issue by rickatnight11** [aetaric/checkrr#33]
On a new install with the default `cron: "@daily"` setting, the user needs to wait up to 24h for the first scan to run.  It would be useful for the user to be able to trigger the next scan manually.

**Comment by HansBaumgaertner** [comment]
Well, that explains why nothing happened after turning on the container for the first time. I didn't look too deeply at the cause as I thought that the 24 hour scans happen 24 hours after the container first starts while doing a first initial scan. I was mistaken. 

I will instead for the initial first-run scan set the cron to `@reboot` which might help.

**Comment by aetaric** [comment]
> Well, that explains why nothing happened after turning on the container for the first time. I didn't look too deeply at the cause as I thought that the 24 hour scans happen 24 hours after the container first starts while doing a first initial scan. I was mistaken.
> 
> I will instead for the initial first-run scan set the cron to `@reboot` which might help.
> 
> **edit** No it did not fix that.

`@daily` is midnight UTC
`@reboot` isn't compatible with checkrr. This isn't using a real cron system. This is using a library that processes a cron line and sets an execution schedule based on that.
If you want checkrr to run right now, edit your container and add `command: -o` so that it passes that flag to checkrr. That is the shortcode for `--run-once` which implies it will run once and exit. There is no other way in 3.0.0 or older to force the scan.

**Comment by rickatnight11** [comment]
That worked, thanks!  Will look forward to the requested feature in the future.

**Comment by HansBaumgaertner** [comment]
Thank you! 

I ended up setting a `cron` for the next minute of my current time and restarting the container which worked too.

**Comment by aetaric** [comment]
<img width="453" alt="Screenshot 2023-01-13 at 2 29 26 AM" src="https://user-images.githubusercontent.com/565454/212285831-c2ff739f-2f3a-4a5d-8b9f-9441de790d4e.png">
Nice run button there... Automatically sets the running state and then disables the button. The button also automatically disables once checkrr starts running on schedule.
