### ISSUE TITLE
Remove deleted files from Bad files list

### ISSUE THREAD

**Issue by psike** [aetaric/checkrr#42]
During first run checkrr detected 400+ unknown flies, and added to bad files list in UI.
After reviewing I decided to delete them manually.
I was expecting these file will be removed from the UI after the next checkrr run.
Currently need to manually select all rows for deletion.

**Comment by aetaric** [comment]
This is currently the expected behavior. The list on the website is meant to inform you of both bad files that checkrr could not replace using configured services, and files that it *did* replace via arr services. If the list is cleared out, how will you know that there were files that checkrr found and sent off to one of the arr services without combing through logs to find out what file it was?

There's a "select all" box already in the table header to make mass removal from the list easy.

**Comment by aetaric** [comment]
It's both a list of things that (potentially) need attention, and a history log. But yeah, having many files is usually only an issue on the first run if ever.
